import {NextRequest,NextResponse} from "next/server"
const cryptoIds:Record<string,string>={BTC:"bitcoin",ETH:"ethereum",SOL:"solana",BNB:"binancecoin",XRP:"ripple",ADA:"cardano",DOGE:"dogecoin",AVAX:"avalanche-2",DOT:"polkadot",LINK:"chainlink",MATIC:"matic-network",PEPE:"pepe",SHIB:"shiba-inu",WIF:"dogwifcoin",BONK:"bonk",AAVE:"aave",UNI:"uniswap",CRV:"curve-dao-token",ARB:"arbitrum",OP:"optimism",HYPE:"hyperliquid"}
const commodity:Record<string,string>={GOLD:"XAU/USD",XAU:"XAU/USD",SILVER:"XAG/USD",XAG:"XAG/USD",OIL:"USOIL",CRUDE:"USOIL"}
const indexSymbols=new Set(["SPX","NDX"])
const CACHE_60={next:{revalidate:60} as const}
const CACHE_300={next:{revalidate:300} as const}
async function gecko(symbol:string){let id=cryptoIds[symbol];if(!id){const s=await fetch(`https://api.coingecko.com/api/v3/search?query=${encodeURIComponent(symbol)}`,CACHE_300);if(!s.ok)throw Error("CoinGecko search unavailable");const j=await s.json();id=j.coins?.[0]?.id}if(!id)throw Error("Crypto asset not found");const r=await fetch(`https://api.coingecko.com/api/v3/simple/price?ids=${encodeURIComponent(id)}&vs_currencies=usd&include_24hr_change=true&include_24hr_vol=true`,CACHE_60);if(!r.ok)throw Error("CoinGecko quote unavailable");const d=(await r.json())[id];if(!d)throw Error("Crypto quote unavailable");return{symbol,price:Number(d.usd),change24h:Number(d.usd_24h_change)||0,volume24h:Number(d.usd_24h_vol)||0,source:"CoinGecko",timestamp:Date.now()}}
async function resolveIndex(symbol:string,key:string){const r=await fetch(`https://api.twelvedata.com/symbol_search?symbol=${encodeURIComponent(symbol)}&apikey=${key}`,CACHE_300);if(!r.ok)throw Error("TwelveData symbol search unavailable");const j=await r.json();const matches=Array.isArray(j.data)?j.data:[];const hit=matches.find((x:any)=>String(x.type||x.instrument_type||"").toLowerCase()==="index")||matches[0];if(!hit?.symbol)throw Error("Index symbol not found");return{symbol:String(hit.symbol),exchange:typeof hit.exchange==="string"?hit.exchange:""}}
async function twelve(symbol:string){const key=process.env.TWELVE_DATA_API_KEY;if(!key)throw Error("TwelveData not configured");const resolved=indexSymbols.has(symbol)?await resolveIndex(symbol,key):{symbol:commodity[symbol]||symbol,exchange:""};const exchange=resolved.exchange?`&exchange=${encodeURIComponent(resolved.exchange)}`:"";const r=await fetch(`https://api.twelvedata.com/quote?symbol=${encodeURIComponent(resolved.symbol)}${exchange}&apikey=${key}`,CACHE_60);if(!r.ok)throw Error("TwelveData unavailable");const d=await r.json();if(d.status==="error")throw Error(d.message||"TwelveData error");const price=Number(d.close);if(!Number.isFinite(price))throw Error("TwelveData returned no price");return{symbol,price,change24h:Number(d.percent_change)||0,volume24h:Number.isFinite(Number(d.volume))?Number(d.volume):null,volumeAvailable:Number.isFinite(Number(d.volume)),source:"TwelveData",timestamp:Date.now()}}
export async function GET(req:NextRequest){const raw=req.nextUrl.searchParams.get("symbol")?.trim()||"";if(!raw)return NextResponse.json({error:"Symbol is required"},{status:400});const symbol=raw.toUpperCase();try{const data=cryptoIds[symbol]||(!symbol.includes("/")&&["BTC","ETH","SOL","BNB","XRP","ADA","DOGE","AVAX","DOT","LINK","MATIC","PEPE","SHIB","WIF","BONK","AAVE","UNI","CRV","ARB","OP","HYPE"].includes(symbol))?await gecko(symbol):await twelve(symbol);return NextResponse.json(data)}catch(e){try{return NextResponse.json(await twelve(symbol))}catch{return NextResponse.json({error:"Market data unavailable",symbol},{status:503})}}}
