const sections = [
  ["1. Who we are", <p key="p">A³ Markets is the trading name used for the A³ Markets service. The service operator is <strong>BILKHU PROJECTS LIMITED</strong> (company number 11345108), registered in England and Wales. For privacy enquiries, contact <a className="text-cyan-400 hover:underline" href="mailto:info@shadowsignals.live">info@shadowsignals.live</a>.</p>],
  ["2. What we collect", <ul key="u" className="list-disc list-inside ml-4 space-y-2"><li>Account and contact information you provide, such as an email address.</li><li>Support or contact messages you send us.</li><li>Technical information needed to operate and secure the service, such as IP address, browser and device information and security logs.</li><li>Usage and performance information generated when you use the service.</li><li>Market data and search inputs submitted to the platform. Market prices and other financial data are not personal data merely because they are displayed.</li></ul>],
  ["3. Why we process personal data", <ul key="u" className="list-disc list-inside ml-4 space-y-2"><li><strong>Contract / requested service:</strong> to provide accounts and platform functionality.</li><li><strong>Legitimate interests:</strong> to operate, secure, troubleshoot and improve A³ Markets, prevent abuse and maintain service reliability.</li><li><strong>Legal obligation:</strong> where processing is required by law.</li><li><strong>Consent:</strong> where the law requires consent, including certain non-essential storage or tracking technologies.</li></ul>],
  ["4. Analytics and Google services", <p key="p">A³ Markets does <strong>not use Google Analytics</strong>. The application currently uses Vercel Web Analytics for service measurement. We do not use analytics to sell personal information or to build advertising profiles. If we introduce another analytics or advertising service, this policy and the applicable consent controls will be updated before that processing starts.</p>],
  ["5. Cookies and device storage", <p key="p">Strictly necessary technologies may be used to provide security, authentication or requested functionality. Non-essential storage or tracking technologies will only be used where an applicable legal exception applies or valid consent has been obtained. You can withdraw consent where consent is the legal basis.</p>],
  ["6. Third-party service providers", <p key="p">A³ Markets uses infrastructure and specialist providers to operate the service. Depending on the feature used, these may include Vercel for hosting and analytics, market-data providers such as Twelve Data and CoinGecko, and AI or data-processing providers used by specific intelligence features. API credentials are server-side secrets and are not intentionally sent to the browser. Third-party providers process information under their own terms and privacy notices and, where applicable, our contractual arrangements.</p>],
  ["7. International transfers", <p key="p">Some providers may process information outside the UK. Where a restricted transfer occurs, we use an applicable UK adequacy regulation, appropriate safeguards or another lawful transfer mechanism, as required by UK data-protection law.</p>],
  ["8. Retention", <p key="p">We keep personal data only for as long as reasonably necessary for the purpose for which it was collected, to provide the service, resolve disputes, maintain security and meet legal obligations. Retention periods vary by data type and are reviewed periodically.</p>],
  ["9. Your rights", <p key="p">Subject to applicable law, you may have rights to access, correct, erase or restrict processing of your personal data, object to certain processing, request portability and withdraw consent where processing relies on consent. To exercise a right, email <a className="text-cyan-400 hover:underline" href="mailto:info@shadowsignals.live">info@shadowsignals.live</a>. We may need to verify your identity before responding.</p>],
  ["10. Security", <p key="p">We use appropriate technical and organisational measures designed to protect personal data against unauthorised access, alteration, disclosure or destruction. Secrets such as API credentials must remain in server-side environment variables and are never intended for client-side exposure. No internet service can guarantee absolute security.</p>],
  ["11. AI and automated analysis", <p key="p">A³ Markets uses automated systems and AI to analyse market information and generate intelligence. These outputs are not personalised financial advice and are not used by us to make decisions about your legal rights or similarly significant matters. Market analysis may be inaccurate or incomplete.</p>],
  ["12. Children", <p key="p">The service is intended for adults and is not directed at children under 18. We do not knowingly collect personal data from children.</p>],
  ["13. Complaints", <p key="p">If you have a privacy concern, please contact us first at <a className="text-cyan-400 hover:underline" href="mailto:info@shadowsignals.live">info@shadowsignals.live</a>. You also have the right to complain to the Information Commissioner's Office (ICO), the UK supervisory authority.</p>],
  ["14. Changes", <p key="p">We may update this policy when our processing activities or legal obligations change. The current version will be published on this page with its effective date.</p>],
] as const

export default function PrivacyPage() {
  return <main className="min-h-screen bg-black text-white py-20"><div className="container mx-auto px-4 max-w-4xl"><h1 className="text-4xl font-bold mb-8 bg-gradient-to-r from-cyan-400 to-cyan-600 bg-clip-text text-transparent">Privacy Policy</h1><p className="text-sm text-gray-400 mb-8">Effective: 31 August 2026</p><div className="space-y-8 text-gray-300">{sections.map(([title, body]) => <section key={title}><h2 className="text-2xl font-semibold text-white mb-4">{title}</h2><div className="leading-7">{body}</div></section>)}</div></div></main>
}
