export type AssetClass="crypto"|"equity"|"fx"|"commodity"|"index"
export interface AssetDefinition{symbol:string;name:string;class:AssetClass;aliases:string[];providerSymbol?:string}
export const ASSET_UNIVERSE:AssetDefinition[]=[
 {symbol:"BTC",name:"Bitcoin",class:"crypto",aliases:["bitcoin","btc"]},{symbol:"ETH",name:"Ethereum",class:"crypto",aliases:["ethereum","eth"]},{symbol:"SOL",name:"Solana",class:"crypto",aliases:["solana","sol"]},{symbol:"HYPE",name:"Hyperliquid",class:"crypto",aliases:["hyperliquid","hype"]},
 {symbol:"XAU/USD",name:"Gold",class:"commodity",aliases:["gold","xau","xauusd","xau/usd"],providerSymbol:"XAU/USD"},{symbol:"XAG/USD",name:"Silver",class:"commodity",aliases:["silver","xag","xagusd","xag/usd"],providerSymbol:"XAG/USD"},{symbol:"WTI",name:"Crude Oil",class:"commodity",aliases:["oil","crude oil","wti"],providerSymbol:"WTI"},
 {symbol:"AAPL",name:"Apple",class:"equity",aliases:["apple","aapl"]},{symbol:"TSLA",name:"Tesla",class:"equity",aliases:["tesla","tsla"]},{symbol:"NVDA",name:"NVIDIA",class:"equity",aliases:["nvidia","nvda"]},{symbol:"MSFT",name:"Microsoft",class:"equity",aliases:["microsoft","msft"]},
 {symbol:"EUR/USD",name:"Euro / US Dollar",class:"fx",aliases:["eurusd","eur/usd","euro dollar","euro"]},{symbol:"GBP/USD",name:"British Pound / US Dollar",class:"fx",aliases:["gbpusd","gbp/usd","pound dollar","pound"]},{symbol:"USD/JPY",name:"US Dollar / Japanese Yen",class:"fx",aliases:["usdjpy","usd/jpy","dollar yen"]},
 {symbol:"SPX",name:"S&P 500",class:"index",aliases:["sp500","s&p 500","s&p","spx"]},{symbol:"NDX",name:"Nasdaq 100",class:"index",aliases:["nasdaq","nasdaq 100","ndx"]}
]
export function searchAssets(query:string,limit=10){const q=query.trim().toLowerCase();if(!q)return ASSET_UNIVERSE.slice(0,limit);return ASSET_UNIVERSE.map((a,i)=>{const exact=a.symbol.toLowerCase()===q||a.name.toLowerCase()===q;const starts=a.symbol.toLowerCase().startsWith(q)||a.name.toLowerCase().startsWith(q);const alias=a.aliases.some(x=>x.toLowerCase()===q);const contains=a.symbol.toLowerCase().includes(q)||a.name.toLowerCase().includes(q)||a.aliases.some(x=>x.toLowerCase().includes(q));const score=exact||alias?100:starts?80:contains?50:0;return{a,score,i}}).filter(x=>x.score>0).sort((x,y)=>y.score-x.score||x.i-y.i).slice(0,limit).map(x=>x.a)}
