"use client"

type Lesson=[string,string,string]
const lessons:Lesson[]=[
["Financial Markets","Financial markets are systems where capital, assets and risk are exchanged. A³ covers crypto, equities, bonds, FX, commodities and the macro forces connecting them.","Use the market context layer before interpreting an individual asset."],
["Stocks & Shares","A share represents ownership in a company and a claim on its economic value. Prices reflect expectations about earnings, growth, risk and liquidity.","A³ can compare company assets with broader equity and macro regimes."],
["Index Funds","An index fund aims to track a market index rather than select individual winners. Examples include funds tracking the S&P 500, FTSE 100 or MSCI World.","Index exposure is a foundation for understanding passive investing and benchmark performance."],
["ETFs","Exchange-traded funds hold a basket of assets and trade on an exchange. They can provide diversified exposure to equities, bonds, commodities or other markets.","A³ treats ETF flows and benchmark behaviour as useful market-context evidence where data is available."],
["Bonds","A bond is a debt instrument: an investor lends money to an issuer in exchange for interest and repayment terms. Bond prices and yields move inversely.","Rates, yields and credit conditions can materially change the environment for risk assets."],
["Hedge Funds","Hedge funds are investment vehicles that can use long and short positions, derivatives, leverage and alternative strategies. The label describes a broad family rather than one strategy.","A³ teaches the mechanics without assuming every hedge fund is directional or inherently risky."],
["Market Makers","Market makers continuously quote buy and sell prices and help provide liquidity. They manage inventory, spreads and risk rather than simply betting on direction.","Liquidity and market structure help explain why price can behave differently in deep and thin markets."],
["Quantitative Trading","Quant strategies use rules, statistics, models and data to make or support trading decisions. They can range from simple systematic rules to complex multi-factor systems.","A³ itself separates deterministic evidence from explanatory language so users can understand the model inputs."],
["Portfolio Diversification","Diversification spreads exposure across assets or risks that do not move identically. It cannot eliminate losses, but can reduce concentration risk.","A³ uses cross-asset context to help identify correlations and changing regimes."],
["Risk & Return","Higher expected return often comes with greater uncertainty or drawdown. A good thesis and appropriate risk are separate questions.","A³ distinguishes confidence in a scenario from the amount of capital that should be exposed."],
["BTC Dominance","BTC dominance is Bitcoin's share of total crypto market capitalisation. Rising dominance can mean capital is concentrating in Bitcoin; falling dominance can indicate rotation.","Read it with ETH/BTC, breadth, liquidity and regime data."],
["ETH/BTC","The ETH/BTC ratio compares Ethereum's price with Bitcoin's price and measures relative strength.","A³ combines it with BTC dominance and breadth when assessing crypto rotation."],
["Altseason","Altseason describes periods when a broad set of non-BTC crypto assets outperform Bitcoin. It is a market condition, not one magic indicator.","Use breadth, ETH/BTC, dominance, liquidity and relative performance together."],
["Blockchain","A blockchain is a shared ledger maintained by a distributed network. Transactions are recorded and verified according to network rules.","A³ connects blockchain mechanics to activity, flows, liquidity and asset context."],
["Bitcoin vs Ethereum","Bitcoin is designed around scarce digital money and settlement. Ethereum is a programmable blockchain supporting smart contracts and applications.","Different network economics mean their market signals should not be treated as identical."],
["L1 vs L2","Layer 1 networks provide base settlement. Layer 2 networks are built around a base chain to improve scalability, cost or throughput.","Architecture helps explain ecosystem activity and token narratives."],
["Stablecoins","Stablecoins aim to maintain a relatively stable reference value and provide crypto-native settlement and liquidity.","Supply, usage and exchange conditions can help explain available crypto liquidity."],
["Exchange Flows","Assets moving onto exchanges can increase immediately available sell-side supply, while withdrawals can reduce exchange-held supply. Context matters.","Use flows alongside price, volume and broader on-chain activity."],
["DXY & Macro","The dollar, interest rates, inflation expectations and global liquidity can influence risk assets. Crypto participates in the wider financial system.","A³ uses cross-asset context rather than analysing crypto in isolation."],
["Gold","Gold is a major global commodity and reserve asset often discussed as a store of value and defensive allocation.","Gold can provide useful context for inflation, real yields and risk sentiment."],
["Equities","Equities represent ownership in companies and are influenced by earnings, valuation, rates, liquidity and investor expectations.","A³ can compare equity regimes with crypto and macro conditions."],
["RSI","RSI measures the speed and magnitude of recent price changes. High RSI means strong momentum, not automatically a sell signal.","A³ uses RSI as one evidence layer inside confluence."],
["MACD","MACD compares moving averages to identify momentum and potential trend changes. Choppy markets can produce false signals.","Combine momentum with structure, regime and volatility."],
["Moving Averages","SMA and EMA calculations smooth price data to expose trend direction. EMAs react faster; SMAs are slower and smoother.","Use averages to frame trend rather than predict exact turns."],
["Volume","Volume measures market participation. Moves supported by meaningful volume can carry more information than moves in thin conditions.","Volume helps distinguish stronger breakouts from weak moves."],
["Support & Resistance","Support and resistance are areas where price has historically encountered demand or supply. They are zones rather than perfect lines.","A³ uses zones for scenarios, targets and invalidation."],
["ATR & Volatility","ATR measures recent trading range and helps contextualise how much an asset normally moves.","Volatility informs risk context and whether a move is unusually large."],
["Confluence","Confluence means independent evidence points toward the same scenario. More indicators do not automatically mean more certainty.","A³ uses confluence to structure evidence, not manufacture certainty."],
["Trend Following","Trend following seeks to participate in sustained directional movement rather than predict every turning point.","Trend, averages, momentum and volume help establish whether a trend is strengthening."],
["Mean Reversion","Mean reversion looks for prices that have moved unusually far from a reference range and may return toward it.","It is highly regime-sensitive because strong trends can remain extended."],
["Breakouts","Breakouts occur when price escapes an established range or level. Confirmation, volume and retests can help distinguish continuation from false breaks.","A³ should show the breakout condition, scenario and invalidation."],
["Position Sizing","Position sizing determines how much capital is exposed to a thesis. A correct view can still produce unacceptable losses if sizing is excessive.","Separate conviction from risk: confidence does not mean unlimited size."],
["Hedging","Hedging means taking an offsetting position or protection designed to reduce the impact of an adverse move in another exposure. Examples include futures, options or currency hedges.","A hedge can reduce downside while also introducing cost, basis and execution risks."],
["Leverage","Leverage increases exposure relative to capital committed. It magnifies both gains and losses and can create liquidation risk.","A³ treats leverage as a risk variable, not a shortcut to higher returns."],
["Drawdown","Drawdown measures the decline from a portfolio or asset's previous peak. Recovery from a large drawdown requires disproportionately large gains.","A³ risk education focuses on preserving capital through different regimes."],
["Invalidation","Every useful thesis needs a condition that would prove it wrong. Invalidation turns an opinion into a testable scenario.","A³ makes key invalidation levels or conditions visible where data supports them."],
]

const sections:[string,string,string[]][]=[
["foundations","Foundations",["Financial Markets","Stocks & Shares","Index Funds","ETFs","Bonds","Portfolio Diversification","Risk & Return"]],
["institutional","Institutional Finance",["Hedge Funds","Market Makers","Quantitative Trading"]],
["markets","Global Markets",["Equities","Bonds","Gold","DXY & Macro"]],
["crypto","Digital Assets & Blockchain",["BTC Dominance","ETH/BTC","Altseason","Blockchain","Bitcoin vs Ethereum","L1 vs L2","Stablecoins","Exchange Flows"]],
["technical","Technical Analysis",["RSI","MACD","Moving Averages","Volume","Support & Resistance","ATR & Volatility"]],
["strategy","Trading & Strategies",["Trend Following","Mean Reversion","Breakouts","Hedging","Leverage"]],
["risk","Risk Intelligence",["Position Sizing","Drawdown","Invalidation","Confluence"]],
]

export function A3LearnHub(){return <main className="min-h-screen bg-[#f5f4ef] text-[#11110f]"><div className="mx-auto max-w-7xl px-5 py-12 md:px-8 md:py-20">
<header className="max-w-4xl"><p className="text-xs font-semibold uppercase tracking-[.3em] text-[#e85d04]">A³ / Learn</p><h1 className="mt-4 text-5xl font-semibold tracking-[-.05em] md:text-7xl">Understand the markets. Then use the intelligence.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-black/55">From index funds and hedge funds to Bitcoin, blockchain, gold, equities, macro, technical analysis and risk — A³ Learn builds financial fluency around the same evidence used by the terminal.</p></header>
<nav className="mt-12 grid gap-4 md:grid-cols-4 lg:grid-cols-7">{sections.map(s=><a key={s[0]} href={`#${s[0]}`} className="rounded-2xl border border-black/10 bg-white p-5 transition hover:-translate-y-0.5 hover:border-[#e85d04]/40"><div className="font-semibold">{s[1]}</div><div className="mt-3 text-xs leading-5 text-black/45">{s[2].slice(0,4).join(" · ")}</div></a>)}</nav>
<section className="mt-16 rounded-3xl bg-[#11110f] p-7 text-white md:p-10"><p className="text-xs uppercase tracking-[.25em] text-[#ff8a45]">A³ decision framework</p><h2 className="mt-3 text-3xl font-semibold">Context → Evidence → Confluence → Scenario → Invalidation</h2><p className="mt-4 max-w-3xl leading-7 text-white/65">A³ does not turn one indicator into a magic signal. It combines independent evidence, identifies where layers agree, defines scenarios and makes invalidation explicit.</p></section>
<div className="mt-16 space-y-16">{sections.map(s=><section id={s[0]} key={s[0]}><div className="mb-7 flex items-end justify-between"><h2 className="text-3xl font-semibold tracking-[-.03em]">{s[1]}</h2><span className="hidden text-xs uppercase tracking-[.2em] text-[#e85d04] md:block">A³ intelligence layer</span></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{s[2].map(name=>{const l=lessons.find(x=>x[0]===name);if(!l)return null;return <article key={name} className="rounded-2xl border border-black/10 bg-white p-6"><h3 className="text-xl font-semibold">{l[0]}</h3><p className="mt-3 leading-7 text-black/60">{l[1]}</p><div className="mt-4 rounded-xl bg-[#f5f4ef] p-4 text-sm leading-6 text-black/55"><strong className="text-[#e85d04]">A³ context:</strong> {l[2]}</div></article>})}</div></section>)}</div>
<section className="mt-16 rounded-3xl border border-[#e85d04]/25 bg-[#fff7f1] p-7 md:p-10"><p className="text-xs font-semibold uppercase tracking-[.25em] text-[#e85d04]">Learn → Terminal</p><h2 className="mt-3 text-3xl font-semibold">Learn a concept. See it live. Build the thesis.</h2><p className="mt-3 max-w-3xl leading-7 text-black/55">Education remains free. The terminal connects these concepts to live market context and analysis. Deeper research and historical layers can sit behind A³ Pro.</p><a href="/dashboard" className="mt-6 inline-flex rounded-xl bg-[#e85d04] px-5 py-3 font-semibold text-white hover:bg-[#c94d00]">Open A³ Terminal →</a></section>
<footer className="mt-16 border-t border-black/10 pt-8 text-sm text-black/45">Educational content only. Market analysis is probabilistic and does not constitute financial advice. Nothing here is personalised investment advice.</footer>
</div></main>}
