"use client"

const lessons = [
  ["BTC Dominance", "BTC dominance is Bitcoin's share of total crypto market capitalisation. Rising dominance can mean capital is concentrating in Bitcoin; falling dominance can indicate rotation into other crypto assets.", "Read it with ETH/BTC, market breadth, liquidity and price structure."],
  ["ETH/BTC", "The ETH/BTC ratio compares Ethereum's price with Bitcoin's price and is a relative-strength gauge. Sustained ETH strength can accompany broader crypto rotation.", "A³ combines ETH/BTC with BTC dominance and regime data when assessing altseason."],
  ["Altseason", "Altseason describes periods when a broad set of non-BTC crypto assets outperform Bitcoin. It is a market condition, not one indicator.", "Use breadth, ETH/BTC, BTC dominance, liquidity and relative performance together."],
  ["Market Regimes", "Markets behave differently in trends, ranges, expansions and contractions. A strategy that works in a trend can fail in a range.", "Regime is the first A³ layer: understand the environment before interpreting indicators."],
  ["Liquidity", "Liquidity describes how easily assets can be bought or sold without materially moving price. Crypto liquidity is influenced by stablecoins, exchange balances, order books and global financial conditions.", "Liquidity changes the reliability of breakouts, trends and market-wide moves."],
  ["Blockchain", "A blockchain is a shared ledger maintained by a distributed network. Transactions are recorded in blocks and linked cryptographically so participants can verify network state.", "A³ connects the technology to markets through activity, flows, liquidity and asset context."],
  ["Bitcoin vs Ethereum", "Bitcoin is primarily designed around scarce digital money and settlement. Ethereum is a programmable blockchain supporting smart contracts and applications.", "Different network economics mean their market signals should not be treated as identical."],
  ["L1 vs L2", "Layer 1 networks provide base settlement. Layer 2 networks are built around a base chain to improve scalability, cost or throughput.", "Understanding the architecture helps explain ecosystem activity and token narratives."],
  ["Stablecoins", "Stablecoins provide crypto-native liquidity and settlement. Changes in supply, exchange balances and usage can help explain available buying power.", "Combine stablecoin conditions with dominance, breadth and risk regime."],
  ["Whales & Smart Money", "Large transactions can matter, but a large transfer is not automatically bullish or bearish. Destination, timing, exchange context and market structure matter.", "A³ treats on-chain movements as evidence rather than guaranteed direction."],
  ["Exchange Flows", "Assets moving onto exchanges can increase immediately available sell-side liquidity, while withdrawals can reduce exchange-held supply. Context is essential.", "Use flows alongside price, volume and broader on-chain activity."],
  ["DXY & Macro", "The dollar, rates, inflation expectations and global liquidity can influence risk assets. Crypto participates in the wider financial system.", "A³ uses cross-asset context so crypto analysis is not isolated from macro conditions."],
  ["Risk-On / Risk-Off", "Risk regimes describe how investors position across assets. Correlations can change quickly during stress, liquidity shocks or strong risk appetite.", "Compare crypto with equities, rates, the dollar and commodities when regime changes."],
  ["RSI", "RSI measures the speed and magnitude of recent price changes. High readings indicate strong momentum, not automatically a sell; low readings indicate weak momentum, not automatically a buy.", "A³ uses RSI as one confirmation layer inside confluence."],
  ["MACD", "MACD compares moving averages to identify momentum and trend changes. Crossovers and divergences can help, but choppy markets create false signals.", "Combine momentum with structure, regime and volatility."],
  ["Moving Averages", "SMAs and EMAs smooth price data to expose trend direction. EMAs react faster; SMAs are slower and smoother.", "Use moving averages to frame trend rather than predict exact turns."],
  ["Volume", "Volume measures participation. A price move supported by meaningful volume can carry more information than a move on thin activity.", "Volume helps distinguish stronger breakouts and trends from weak moves."],
  ["Support & Resistance", "Support and resistance are areas where price has historically encountered demand or supply. They are zones rather than perfect lines.", "A³ uses these zones for scenarios, targets and invalidation."],
  ["ATR & Volatility", "ATR measures recent trading range and helps contextualise how much an asset normally moves.", "Volatility informs risk sizing and whether a move is unusually large."],
  ["Bollinger Bands", "Bollinger Bands place volatility bands around a moving average. Expansion indicates rising volatility; contraction indicates compression.", "Compression can frame a breakout scenario, but direction still needs confirmation."],
  ["Fibonacci", "Fibonacci retracement levels are commonly used to map potential pullback zones within a move.", "Treat them as areas of interest requiring price and context confirmation."],
  ["Confluence", "Confluence means independent evidence points toward the same scenario. More indicators do not automatically mean more certainty.", "A³ uses confluence to structure evidence, not manufacture certainty."],
  ["Trend Following", "Trend following seeks to participate in sustained directional movement instead of predicting every turning point.", "Trend structure, averages, momentum and volume establish whether a trend is strengthening."],
  ["Mean Reversion", "Mean reversion looks for prices that have moved unusually far from a reference range and may return toward it.", "It is highly regime-sensitive: strong trends can remain extended."],
  ["Breakouts", "Breakouts occur when price escapes an established range or level. Confirmation, volume and retests help distinguish continuation from false breaks.", "A³ should show the breakout condition, scenario and invalidation."],
  ["Position Sizing", "Position sizing determines how much capital is exposed to a thesis. A correct view can still produce unacceptable losses if sizing is excessive.", "Separate conviction from risk: confidence does not mean unlimited size."],
  ["Invalidation", "Every useful thesis needs a condition that would prove it wrong. Invalidation turns an opinion into a testable scenario.", "A³ should make the key invalidation level or condition visible."],
]

const sections = [
  ["market", "Market Structure", ["BTC Dominance", "ETH/BTC", "Altseason", "Market Regimes", "Liquidity"]],
  ["blockchain", "Blockchain & On-Chain", ["Blockchain", "Bitcoin vs Ethereum", "L1 vs L2", "Stablecoins", "Whales & Smart Money", "Exchange Flows"]],
  ["macro", "Macro & Cross-Asset", ["DXY & Macro", "Risk-On / Risk-Off", "Global Liquidity", "Gold", "Equities", "Rates"]],
  ["technical", "Technical Analysis", ["RSI", "MACD", "Moving Averages", "Volume", "Support & Resistance", "ATR & Volatility", "Bollinger Bands", "Fibonacci"]],
  ["decision", "Decision & Risk", ["Confluence", "Trend Following", "Mean Reversion", "Breakouts", "Position Sizing", "Invalidation"]],
]

export function A3LearnHub() {
  return <main className="min-h-screen bg-[#f5f4ef] text-[#11110f]"><div className="mx-auto max-w-7xl px-5 py-12 md:px-8 md:py-20">
    <header className="max-w-4xl"><p className="text-xs font-semibold uppercase tracking-[.3em] text-[#e85d04]">A³ / Learn</p><h1 className="mt-4 text-5xl font-semibold tracking-[-.05em] md:text-7xl">Understand the market. Then use the intelligence.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-black/55">A³ Learn explains the market layers behind the terminal — from BTC dominance and blockchain mechanics to liquidity, macro, technical analysis and risk.</p></header>
    <nav className="mt-12 grid gap-4 md:grid-cols-5">{sections.map(s=><a key={s[0]} href={`#${s[0]}`} className="rounded-2xl border border-black/10 bg-white p-5 transition hover:-translate-y-0.5 hover:border-[#e85d04]/40"><div className="font-semibold">{s[1]}</div><div className="mt-3 text-xs leading-5 text-black/45">{s[2].join(" · ")}</div></a>)}</nav>
    <section className="mt-16 rounded-3xl bg-[#11110f] p-7 text-white md:p-10"><p className="text-xs uppercase tracking-[.25em] text-[#ff8a45]">A³ decision framework</p><h2 className="mt-3 text-3xl font-semibold">Context → Evidence → Confluence → Scenario → Invalidation</h2><p className="mt-4 max-w-3xl leading-7 text-white/65">A³ does not turn one indicator into a magic signal. It combines independent evidence, identifies where layers agree, defines scenarios and makes invalidation explicit.</p></section>
    <div className="mt-16 space-y-16">{sections.map((s,si)=><section id={s[0]} key={s[0]}><div className="mb-7 flex items-end justify-between"><h2 className="text-3xl font-semibold tracking-[-.03em]">{s[1]}</h2><span className="hidden text-xs uppercase tracking-[.2em] text-[#e85d04] md:block">A³ intelligence layer</span></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{lessons.filter((_,i)=>i%5===si || (si===0 && i<5)).map((l,i)=><article key={`${l[0]}-${i}`} className="rounded-2xl border border-black/10 bg-white p-6"><h3 className="text-xl font-semibold">{l[0]}</h3><p className="mt-3 leading-7 text-black/60">{l[1]}</p><div className="mt-4 rounded-xl bg-[#f5f4ef] p-4 text-sm leading-6 text-black/55"><strong className="text-[#e85d04]">A³ context:</strong> {l[2]}</div></article>)}</div></section>)}</div>
    <section className="mt-16 rounded-3xl border border-[#e85d04]/25 bg-[#fff7f1] p-7 md:p-10"><p className="text-xs font-semibold uppercase tracking-[.25em] text-[#e85d04]">Learn → Terminal</p><h2 className="mt-3 text-3xl font-semibold">Learn a concept. See it live. Build the thesis.</h2><p className="mt-3 max-w-3xl leading-7 text-black/55">Education remains free. The terminal turns these concepts into live market context. A³ Pro can later add deeper historical analysis, richer cross-asset intelligence and advanced research layers.</p><a href="/dashboard" className="mt-6 inline-flex rounded-xl bg-[#e85d04] px-5 py-3 font-semibold text-white hover:bg-[#c94d00]">Open A³ Terminal →</a></section>
    <footer className="mt-16 border-t border-black/10 pt-8 text-sm text-black/45">Educational content only. Market analysis is probabilistic and does not constitute financial advice.</footer>
  </div></main>
}
