"use client"
import { X, Activity, AlertCircle, ShieldAlert, Target, TrendingUp, BookOpen, Layers3 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { useEffect, useState } from "react"
import { ExportAnalysis } from "@/components/export-analysis"
import { useWatchlist } from "@/hooks/use-watchlist"
import { SimplePriceDisplay } from "@/components/simple-price-display"

interface AnalysisData { symbol?:string; currentPrice?:number|null; change24h?:number|null; aiRecommendation?:"Buy"|"Sell"|"Hold"; signalStrength?:number|null; indicators?:{rsi?:{value?:number|null;signal?:string};trend?:string;macd?:string;stochasticRsi?:number|null}; technicalIndicators?:{rsi?:number|null;stochasticRsi?:number|null;support?:number|null;resistance?:number|null}; supportResistance?:{support1?:number|null;support2?:number|null;resistance1?:number|null;resistance2?:number|null}; marketInsight?:string; multiTimeframe?:Record<string,{signal?:"Buy"|"Sell"|"Hold";confidence?:number|null}|null> }
interface Props { symbol:string; onClose:()=>void }
const safeText=(v:unknown,f="—")=>typeof v==="string"&&v.trim()?v:f
const safeSignal=(v:unknown):"Buy"|"Sell"|"Hold"=>v==="Buy"||v==="Sell"?v:"Hold"
const num=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?v:null
const fmt=(v:number|null|undefined,d=2)=>v==null||!Number.isFinite(v)?"—":Number(v).toLocaleString("en-US",{minimumFractionDigits:0,maximumFractionDigits:d})
const fmtPrice=(v:number|null|undefined)=>fmt(v,0)
export function ComprehensiveAnalysisPanel({symbol,onClose}:Props){
 const[data,setData]=useState<AnalysisData|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const{addToWatchlist,removeFromWatchlist,isInWatchlist}=useWatchlist()
 useEffect(()=>{const c=new AbortController();const t=setTimeout(()=>c.abort(),20000);setLoading(true);setError(null);setData(null);(async()=>{try{const r=await fetch(`/api/comprehensive-analysis?symbol=${encodeURIComponent(symbol)}`,{cache:"no-store",signal:c.signal});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||`Analysis API returned ${r.status}`);setData(b&&typeof b==="object"?b:null)}catch(e){setError(e instanceof DOMException&&e.name==="AbortError"?"Analysis timed out. The market-data provider may be temporarily unavailable.":e instanceof Error?e.message:"Unable to load analysis.")}finally{clearTimeout(t);setLoading(false)}})();return()=>{clearTimeout(t);c.abort()}},[symbol])
 if(loading)return <Overlay><Activity className="mx-auto mb-4 h-9 w-9 animate-pulse text-[#e85d04]"/><div className="font-medium">Building A³ intelligence for {symbol}…</div><div className="mt-2 text-xs text-black/45">Analysing market structure, momentum and risk</div></Overlay>
 if(error||!data)return <Overlay><AlertCircle className="mx-auto mb-4 h-9 w-9 text-[#e85d04]"/><div className="mb-2 font-semibold">Analysis unavailable</div><div className="mb-5 text-sm text-black/50">{error||"No analysis was returned."}</div><div className="flex justify-center gap-2"><Button onClick={onClose} variant="outline">Close</Button><Button onClick={()=>window.location.reload()} className="bg-[#e85d04] text-white hover:bg-[#c94d00]">Retry</Button></div></Overlay>
 const inWatchlist=isInWatchlist(symbol);const tfEntries=Object.entries(data.multiTimeframe&&typeof data.multiTimeframe==="object"?data.multiTimeframe:{}).filter(([,d])=>d&&typeof d==="object");const trend=safeText(data.indicators?.trend);const macd=safeText(data.indicators?.macd);const stoch=num(data.technicalIndicators?.stochasticRsi)??num(data.indicators?.stochasticRsi);const price=num(data.currentPrice);const support=num(data.technicalIndicators?.support);const resistance=num(data.technicalIndicators?.resistance);const signal=safeSignal(data.aiRecommendation);const confidence=num(data.signalStrength)??0
 const alignment=tfEntries.map(([,d])=>d).filter(Boolean) as Array<{signal?:"Buy"|"Sell"|"Hold";confidence?:number|null}>;const bullish=alignment.filter(x=>safeSignal(x.signal)==="Buy").length;const alignmentText=alignment.length?`${bullish}/${alignment.length} timeframes bullish`:"No timeframe alignment available";
 const regime=signal==="Buy"?"Bullish regime":signal==="Sell"?"Bearish regime":"Mixed / range regime";
 const location=price!=null&&support!=null&&resistance!=null?(price<=support*1.015?"Near support":price>=resistance*.985?"Near resistance":"Inside current range"):"Insufficient range data";
 const thesis=signal==="Buy"?`${symbol} currently has a bullish A³ state. Momentum and timeframe alignment support the positive regime, but the quality of the setup depends on price location and whether resistance can be cleared.`:signal==="Sell"?`${symbol} currently has a bearish A³ state. Momentum and timeframe alignment favour caution while the current structure remains below key resistance.`:`${symbol} is currently in a mixed A³ state. The evidence is not sufficiently aligned for a strong directional thesis.`;
 const bullCase=resistance!=null?`A sustained move above $${fmtPrice(resistance)} would strengthen the bullish structure and confirm that buyers are absorbing the current supply zone.`:"A confirmed breakout through the nearest resistance would strengthen the bullish structure.";
 const bearCase=support!=null?`A decisive close below $${fmtPrice(support)} would weaken the current structure and invalidate the immediate bullish thesis.`:"A decisive break below the nearest structural support would weaken the thesis.";
 return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/70 p-3 md:p-5 backdrop-blur-md"><div className="mx-auto flex min-h-full max-w-6xl items-start justify-center py-3 md:py-6"><div className="w-full overflow-hidden rounded-[28px] border border-black/10 bg-[#f5f4ef] text-[#11110f] shadow-2xl">
   <div className="sticky top-0 z-20 flex items-center justify-between border-b border-black/10 bg-[#f5f4ef]/95 p-4 md:p-5 backdrop-blur"><div><p className="text-[10px] font-bold uppercase tracking-[.28em] text-[#e85d04]">A³ / Intelligence Terminal</p><h2 className="mt-1 text-xl md:text-2xl font-semibold tracking-[-.04em]">Analysis for {symbol}</h2></div><div className="flex gap-2"><Button onClick={()=>inWatchlist?removeFromWatchlist(symbol):addToWatchlist(symbol)} variant="outline" size="sm">{inWatchlist?"In Watchlist":"Add to Watchlist"}</Button><ExportAnalysis symbol={symbol} data={data}/><Button onClick={onClose} variant="ghost" size="icon"><X className="h-5 w-5"/></Button></div></div>
   <div className="space-y-5 p-4 md:p-7"><SimplePriceDisplay symbol={symbol} currentPrice={data.currentPrice??0}/>
    <section className="rounded-3xl border border-[#e85d04]/25 bg-white p-5 md:p-6 shadow-sm"><div className="grid gap-6 md:grid-cols-[1fr_auto]"><div><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.2em] text-[#e85d04]"><Layers3 className="h-4 w-4"/> A³ thesis</div><div className="mt-2 flex flex-wrap items-end gap-3"><h3 className="text-3xl font-semibold tracking-[-.04em]">{signal}</h3><span className={`mb-1 rounded-full px-3 py-1 text-xs font-semibold ${signal==="Buy"?"bg-emerald-100 text-emerald-800":signal==="Sell"?"bg-red-100 text-red-800":"bg-orange-100 text-orange-800"}`}>{fmt(confidence,0)}% confidence</span></div><p className="mt-3 max-w-3xl text-sm leading-6 text-black/65">{thesis}</p></div><div className="md:min-w-[210px] md:text-right"><div className="text-xs uppercase tracking-[.16em] text-black/40">Current price</div><div className="mt-1 text-3xl font-semibold tabular-nums">${fmtPrice(price)}</div><div className={num(data.change24h)!=null&&num(data.change24h)!>=0?"text-emerald-700":"text-red-700"}>{num(data.change24h)!=null&&num(data.change24h)!>=0?"+":""}{fmt(num(data.change24h))}% (24h)</div><div className="mt-2 text-xs font-medium text-black/45">{regime} · {location}</div></div></div></section>
    <section className="grid gap-3 md:grid-cols-4"><Metric title="RSI" value={fmt(data.technicalIndicators?.rsi)} tone="signal"/><Metric title="Trend" value={trend} tone="signal"/><Metric title="MACD" value={macd} tone="signal"/><Metric title="Stoch RSI" value={fmt(stoch)} tone="signal"/></section>
    <section className="rounded-3xl border border-black/10 bg-white p-5"><SectionTitle icon={<TrendingUp className="h-4 w-4"/>}>Confluence</SectionTitle><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Factor label="Trend" value={trend}/><Factor label="MACD" value={macd}/><Factor label="Timeframe" value={alignmentText}/><Factor label="Price location" value={location}/></div></section>
    <section className="rounded-3xl border border-black/10 bg-white p-5"><SectionTitle icon={<Layers3 className="h-4 w-4"/>}>Timeframe alignment</SectionTitle><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-5">{tfEntries.map(([t,d])=>{const sg=safeSignal(d?.signal);return <div key={t} className="text-center"><div className="mb-1 text-xs text-black/40">{t}</div><div className={`rounded-2xl border p-3 ${sg==="Buy"?"border-emerald-600/25 bg-emerald-50":sg==="Sell"?"border-red-600/25 bg-red-50":"border-black/10 bg-[#f5f4ef]"}`}><div className="font-semibold">{sg}</div><div className="text-xs text-black/45">{fmt(d?.confidence,0)}%</div></div></div>})}</div></section>
    <section className="grid gap-4 md:grid-cols-2"><Scenario icon={<Target className="h-4 w-4"/>} title="Bull case" text={bullCase} tone="bull"/><Scenario icon={<ShieldAlert className="h-4 w-4"/>} title="Risk / invalidation" text={bearCase} tone="risk"/></section>
    <section className="grid gap-4 md:grid-cols-3"><Metric title="Support" value={`$${fmtPrice(support)}`}/><Metric title="Resistance" value={`$${fmtPrice(resistance)}`}/><Metric title="Next review" value="Next major timeframe close"/></section>
    <section className="rounded-3xl border border-black/10 bg-[#11110f] p-5 text-white"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.2em] text-[#ff8a45]"><BookOpen className="h-4 w-4"/> Market intelligence</div><p className="mt-3 text-sm leading-7 text-white/75">{safeText(data.marketInsight,"A³ has no additional market-context narrative available for this asset yet.")}</p></section>
    <div className="rounded-2xl border border-black/10 bg-black/[.035] px-4 py-3 text-[11px] leading-5 text-black/50"><strong className="text-black/65">A³ analysis is informational, not personalised financial advice.</strong> Signals, scenarios and confidence scores are model outputs and can be wrong. They are not instructions to buy, sell or hold an asset. Cryptoassets and other markets can lose substantial or all of their value.</div>
   </div></div></div></div>
}
function SectionTitle({children,icon}:{children:React.ReactNode;icon:React.ReactNode}){return <h3 className="flex items-center gap-2 text-sm font-semibold">{icon}{children}</h3>}
function Factor({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-[#f5f4ef] p-4"><div className="text-[11px] uppercase tracking-[.12em] text-black/40">{label}</div><div className="mt-1 truncate text-sm font-semibold">{value}</div></div>}
function Scenario({icon,title,text,tone}:{icon:React.ReactNode;title:string;text:string;tone:"bull"|"risk"}){return <div className={`rounded-3xl border p-5 ${tone==="bull"?"border-emerald-700/20 bg-emerald-50/70":"border-red-700/20 bg-red-50/70"}`}><div className={`flex items-center gap-2 text-sm font-semibold ${tone==="bull"?"text-emerald-800":"text-red-800"}`}>{icon}{title}</div><p className="mt-3 text-sm leading-6 text-black/65">{text}</p></div>}
function Overlay({children}:{children:React.ReactNode}){return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/60 p-4 backdrop-blur-md"><div className="w-full max-w-md rounded-3xl border border-[#e85d04]/20 bg-[#f5f4ef] p-8 text-center shadow-2xl">{children}</div></div>}
function Metric({title,value,tone}:{title:string;value:string;tone?:"signal"}){return <div className={`rounded-2xl border p-4 ${tone?"border-[#e85d04]/15 bg-white":"border-black/10 bg-white"}`}><div className="text-xs text-black/40">{title}</div><div className="mt-1 truncate text-lg font-semibold">{value}</div></div>}
