"use client"
import { useState } from "react"
import { BookOpen, X } from "lucide-react"

const LESSONS:Record<string,{title:string;body:string;learn:string}>={
 RSI:{title:"RSI — Relative Strength Index",body:"RSI measures the speed and magnitude of recent price changes. A high reading indicates strong recent momentum; it is not, by itself, a sell signal.",learn:"/learn#technical"},
 MACD:{title:"MACD — Momentum",body:"MACD compares moving averages to help identify momentum and potential trend changes. It works best as one layer of evidence rather than a standalone signal.",learn:"/learn#technical"},
 "Stoch RSI":{title:"Stoch RSI",body:"Stoch RSI applies the stochastic calculation to RSI, making it more sensitive to short-term momentum shifts. Because it is sensitive, it can produce frequent signals in choppy markets.",learn:"/learn#technical"},
 Trend:{title:"Trend & Moving Averages",body:"Moving averages smooth price data to expose the underlying direction of a market. A³ uses trend as structural context, not as a promise of future price.",learn:"/learn#technical"},
 "BTC Dominance":{title:"BTC Dominance",body:"BTC dominance is Bitcoin's share of total crypto market capitalisation. Rising dominance can indicate concentration in Bitcoin; falling dominance can indicate rotation, but context matters.",learn:"/learn#crypto"},
 "ETH/BTC":{title:"ETH/BTC",body:"The ETH/BTC ratio compares Ethereum's price with Bitcoin's price and is a useful measure of relative strength and crypto rotation.",learn:"/learn#crypto"},
 Confluence:{title:"Confluence",body:"Confluence means multiple independent evidence layers point toward a similar scenario. More indicators do not automatically mean more certainty.",learn:"/learn#risk"},
 "Support / Resistance":{title:"Support & Resistance",body:"Support and resistance are zones where price has historically encountered demand or supply. A³ uses them to frame scenarios and invalidation, not as perfect lines.",learn:"/learn#technical"},
 Hedging:{title:"Hedging",body:"Hedging means taking an offsetting position or protection designed to reduce the impact of an adverse move in another exposure. Hedges have costs and can introduce basis or execution risk.",learn:"/learn#strategy"},
 Leverage:{title:"Leverage",body:"Leverage increases exposure relative to committed capital. It magnifies gains and losses and can introduce liquidation risk.",learn:"/learn#strategy"},
}

export function LearnContext({term}:{term:string}){const lesson=LESSONS[term];const[open,setOpen]=useState(false);if(!lesson)return null;return <><button type="button" onClick={()=>setOpen(true)} className="inline-flex items-center gap-1 rounded-md text-left text-[#e85d04] hover:underline" aria-label={`Learn about ${lesson.title}`}>{term}<BookOpen className="h-3 w-3"/></button>{open&&<div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm" onClick={()=>setOpen(false)}><div role="dialog" aria-modal="true" aria-labelledby={`lesson-${term}`} className="w-full max-w-md rounded-3xl border border-[#e85d04]/20 bg-[#f5f4ef] p-6 text-[#11110f] shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.25em] text-[#e85d04]">A³ Learn</p><h3 id={`lesson-${term}`} className="mt-2 text-xl font-semibold">{lesson.title}</h3></div><button type="button" onClick={()=>setOpen(false)} className="rounded-lg p-2 hover:bg-black/5" aria-label="Close"><X className="h-5 w-5"/></button></div><p className="mt-4 text-sm leading-7 text-black/65">{lesson.body}</p><a href={lesson.learn} onClick={()=>setOpen(false)} className="mt-5 inline-flex rounded-xl bg-[#e85d04] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#c94d00]">Open full lesson →</a></div></div>}</>}
