import type { A3ForecastRecord } from "./engine-pipeline"
import { calibrate, evaluateForecast, type Outcome } from "./calibration"

const cfg=()=>({url:process.env.SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL,key:process.env.SUPABASE_SERVICE_ROLE_KEY})
const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms))
async function query(path:string,init:RequestInit={}){const{url,key}=cfg();if(!url||!key)return null;let lastError:unknown;for(let attempt=0;attempt<3;attempt++){try{const r=await fetch(`${url.replace(/\/$/,"")}/rest/v1/${path}`,{...init,headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",...(init.headers||{})},cache:"no-store"});if(!r.ok)throw Error(`Supabase ${r.status}`);return r.status===204?null:r.json()}catch(e){lastError=e;if(attempt<2)await sleep(200*(attempt+1))}}throw lastError}

export async function persistForecast(f:A3ForecastRecord,price:number){return query("a3_forecasts",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({symbol:f.symbol,captured_at:new Date(f.capturedAt).toISOString(),price,signal:f.signal,confidence:f.confidence,score:f.score,scenario:f.scenario,regime:f.regime,horizon:f.horizon})})}

export async function resolveForecasts(symbol:string,price:number,capturedAt=Date.now()){const states=await query(`a3_forecasts?select=id,symbol,captured_at,price,signal,confidence,score,scenario,regime,horizon&symbol=eq.${encodeURIComponent(symbol.toUpperCase())}&captured_at=lte.${encodeURIComponent(new Date(capturedAt).toISOString())}&limit=500`);if(!Array.isArray(states))return{resolved:0};let resolved=0;for(const f of states){const target=new Date(new Date(f.captured_at).getTime()+horizonMs(f.horizon));if(target.getTime()>capturedAt)continue;const existing=await query(`a3_forecast_outcomes?select=id&forecast_id=eq.${f.id}&limit=1`);if(Array.isArray(existing)&&existing.length)continue;const ret=(price-Number(f.price))/Number(f.price)*100;const outcome=evaluateForecast({symbol:f.symbol,capturedAt:new Date(f.captured_at).getTime(),signal:f.signal,confidence:Number(f.confidence),score:Number(f.score),horizon:f.horizon},ret);await query("a3_forecast_outcomes",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({forecast_id:f.id,target_at:target.toISOString(),actual_return_pct:ret,actual_direction:outcome.actualDirection,correct:outcome.correct})});resolved++}return{resolved}}

function horizonMs(h:string){return({"1h":3600000,"4h":14400000,"24h":86400000,"7d":604800000}[h]??86400000)}

export async function getCalibration(symbol?:string){const filter=symbol?`&symbol=eq.${encodeURIComponent(symbol.toUpperCase())}`:"";const rows=await query(`a3_forecasts?select=confidence,a3_forecast_outcomes(correct,actual_return_pct)${filter}&limit=5000`);if(!Array.isArray(rows))return[];return calibrate(rows.filter((r:any)=>r.a3_forecast_outcomes).map((r:any)=>({confidence:Number(r.confidence),correct:Boolean(r.a3_forecast_outcomes.correct),actualReturnPct:Number(r.a3_forecast_outcomes.actual_return_pct)})))}
