const sections = [
  ["1. Agreement", <p key="p">These Terms of Service govern your use of A³ Markets. A³ Markets is the service operated by <strong>BILKHU PROJECTS LIMITED</strong> (company number 11345108), registered in England and Wales. By using the service, you agree to these Terms and the Privacy Policy. If you do not agree, do not use the service.</p>],
  ["2. The service", <p key="p">A³ Markets provides market intelligence, technical analysis, AI-assisted analysis, market data, cycle analysis, confluence scoring, forecasts and related educational tools. Features and data sources may change as the service is maintained.</p>],
  ["3. No financial advice", <div key="d" className="space-y-4"><p className="font-semibold text-red-400">A³ Markets is an information and market-intelligence service, not a financial adviser, investment manager, broker or exchange.</p><p>Nothing on the platform constitutes personal financial, investment, tax or legal advice, an offer to buy or sell an asset, or a recommendation that a particular transaction is suitable for you. You make your own decisions and should obtain independent professional advice where appropriate.</p><p>Trading and investing can result in substantial or total loss of capital. Past performance, backtests, forecasts, historical analogues and AI outputs do not guarantee future results.</p></div>],
  ["4. Market data and AI", <p key="p">Market data is obtained from third-party providers and may be delayed, unavailable, incomplete or inaccurate. A³ intelligence combines multiple inputs and may contain model errors, assumptions or false signals. You must independently verify information before acting on it.</p>],
  ["5. Forecasts and backtesting", <p key="p">Historical tests and forecast scores are analytical tools, not promises of performance. Backtests can be affected by data quality, survivorship bias, look-ahead bias, execution assumptions, liquidity and other limitations. Results shown by A³ Markets should not be treated as a representation of likely future returns.</p>],
  ["6. Acceptable use", <ul key="u" className="list-disc list-inside ml-4 space-y-2"><li>Use the service lawfully and responsibly.</li><li>Do not attempt to bypass authentication, rate limits or security controls.</li><li>Do not probe, scrape, reverse engineer or interfere with private administrative systems.</li><li>Do not introduce malware or attempt unauthorised access to accounts, data or infrastructure.</li><li>Do not copy or commercially redistribute A³ intellectual property without permission.</li><li>Do not use the service to facilitate fraud, market manipulation or other unlawful activity.</li></ul>],
  ["7. Accounts and security", <p key="p">If an account is provided, you are responsible for keeping your credentials secure and for activity carried out through your account. Notify us promptly if you suspect unauthorised access. We may suspend access where reasonably necessary to protect users, the service or our infrastructure.</p>],
  ["8. Intellectual property", <p key="p">A³ Markets and its underlying software, designs, branding, analytical methods, documentation and content are owned by or licensed to the service operator and protected by applicable intellectual-property laws. These Terms give you a limited, revocable, non-exclusive right to use the service for its intended purpose; they do not transfer ownership.</p>],
  ["9. Third-party services", <p key="p">The service may depend on third-party data, hosting, AI and infrastructure providers. We are not responsible for third-party outages, data errors, changes, pricing, terms or privacy practices. A³ Markets does not receive or expose third-party API credentials through the public client interface as part of normal operation.</p>],
  ["10. Availability and changes", <p key="p">We aim to keep A³ Markets available and reliable but do not guarantee uninterrupted operation. We may modify, suspend or discontinue features where reasonably necessary for maintenance, security, legal compliance or development.</p>],
  ["11. Liability", <p key="p">To the maximum extent permitted by law, we are not liable for losses arising from your investment or trading decisions, reliance on market data or analysis, third-party service failures, interruptions, or events outside our reasonable control. Nothing in these Terms excludes liability that cannot lawfully be excluded, including liability for fraud or for death or personal injury caused by negligence.</p>],
  ["12. Consumer rights", <p key="p">Nothing in these Terms removes or limits mandatory rights you may have under applicable consumer-protection law. Where the law requires a particular remedy, that remedy remains available to you.</p>],
  ["13. Suspension and termination", <p key="p">We may suspend or terminate access where you materially breach these Terms, misuse the service, create a security risk, engage in unlawful activity, or where continued provision is no longer reasonably possible. You may stop using the service at any time.</p>],
  ["14. Governing law", <p key="p">These Terms are governed by the laws of England and Wales, subject to any mandatory consumer protections that apply to you. The courts of England and Wales will have jurisdiction, except where applicable law gives a consumer the right to bring proceedings elsewhere.</p>],
  ["15. Contact", <p key="p">Questions, complaints or legal notices should be sent to <a className="text-cyan-400 hover:underline" href="mailto:info@shadowsignals.live">info@shadowsignals.live</a>.</p>],
] as const

export default function TermsPage() {
  return <main className="min-h-screen bg-black text-white py-20"><div className="container mx-auto px-4 max-w-4xl"><h1 className="text-4xl font-bold mb-8 bg-gradient-to-r from-cyan-400 to-cyan-600 bg-clip-text text-transparent">Terms of Service</h1><p className="text-sm text-gray-400 mb-8">Effective: 31 August 2026</p><div className="space-y-8 text-gray-300">{sections.map(([title, body]) => <section key={title}><h2 className="text-2xl font-semibold text-white mb-4">{title}</h2><div className="leading-7">{body}</div></section>)}</div></div></main>
}
