import { NextRequest, NextResponse } from "next/server"
import { decide } from "@/lib/intelligence/decision-engine"
import { runA3Pipeline } from "@/lib/intelligence/engine-pipeline"
import { persistForecast } from "@/lib/intelligence/forecast-store"
import { runCrossAsset } from "@/lib/intelligence/cross-asset"
import { runDerivativesEngine } from "@/lib/intelligence/derivatives-engine"
import { runDivergenceEngine } from "@/lib/intelligence/divergence-engine"
import { runCycleEngine } from "@/lib/intelligence/cycle-engine"
export const dynamic="force-dynamic"
const clamp=(n:number)=>Math.max(0,Math.min(100,Math.round(n)))
const n=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?v:null
export async function GET(req:NextRequest){const symbol=req.nextUrl.searchParams.get("symbol")?.toUpperCase();if(!symbol)return NextResponse.json({error:"Symbol is required"},{status:400});try{const base=new URL("/api/comprehensive-analysis",req.url);base.searchParams.set("symbol",symbol);const cycleUrl=new URL("/api/market-cycle",req.url);const [ar,cr]=await Promise.all([fetch(base,{cache:"no-store"}),fetch(cycleUrl,{cache:"no-store"})]);const analysis=await ar.json(),c=await cr.json();if(!ar.ok)return NextResponse.json(analysis,{status:ar.status});
 const tactical=clamp(Number(analysis.signalStrength)||50);const trend=String(analysis.indicators?.trend||"").toLowerCase();const macd=String(analysis.indicators?.macd||"").toLowerCase();const strategic=clamp(50+(trend.includes("up")||trend.includes("bull")?20:trend.includes("down")||trend.includes("bear")?-20:0)+(macd.includes("bull")?10:macd.includes("bear")?-10:0));const rawCycle=Number(c.bullMarket?.cycleProgress);const cycleScore=clamp(Number.isFinite(rawCycle)?(rawCycle<15?35:rawCycle<40?55:rawCycle<75?70:85):50);const breadth=clamp(50+(Number(c.altseason?.progress)||0)/4);const risk=clamp(65-(Number(c.bullMarket?.topRiskScore)||0));
 const price=n(analysis.currentPrice)??0,change=n(analysis.change24h)??0,rsi=n(analysis.technicalIndicators?.rsi),btcDom=n(c.altseason?.btcDominance),ethBtc=n(c.altseason?.ethBtcRatio);const derivatives=runDerivativesEngine({fundingRate:n(analysis.derivatives?.fundingRate),openInterestChangePct:n(analysis.derivatives?.openInterestChangePct),longShortRatio:n(analysis.derivatives?.longShortRatio),liquidationsUsd:n(analysis.derivatives?.liquidationsUsd),priceChangePct:change});const divergence=runDivergenceEngine({priceChangePct:change,volumeChangePct:n(analysis.volumeChangePct),momentumChange:n(analysis.momentumChange),fundingRate:n(analysis.derivatives?.fundingRate),openInterestChangePct:n(analysis.derivatives?.openInterestChangePct),breadthChange:n(c.altseason?.progressChange)});const cycle=runCycleEngine({price,ath:n(c.bullMarket?.ath)??price,drawdownPct:n(c.bullMarket?.drawdownPct),rsi,btcDominance:btcDom,ethBtc});const cross=runCrossAsset({btcReturn:n(c.crossAsset?.btcReturn),ethReturn:n(c.crossAsset?.ethReturn),btcDominance:btcDom,ethBtcReturn:n(c.crossAsset?.ethBtcReturn),goldReturn:n(c.crossAsset?.goldReturn),dxyReturn:n(c.crossAsset?.dxyReturn),spxReturn:n(c.crossAsset?.spxReturn),nasdaqReturn:n(c.crossAsset?.nasdaqReturn)});
 const market={...analysis.marketState, symbol, price, currentPrice:price, indicators:{rsi:rsi??50,macd:analysis.indicators?.macd,macdSignal:analysis.indicators?.macdSignal},trend:analysis.indicators?.trend||"neutral"};const pipeline=runA3Pipeline(market,{derivatives:analysis.derivatives||null,flow:analysis.flow||null,historical:analysis.historical||null,breadthScore:breadth,cycleScore,strategicScore:strategic,cycle,divergence},"1d");const result=decide({tacticalScore:tactical,strategicScore:strategic,cycleScore,breadthScore:breadth,riskScore:risk});
 await persistForecast(pipeline.forecast,price).catch(e=>console.error("Forecast persistence failed",e));return NextResponse.json({symbol,price,change24h:change,thesis:result.thesis,score:pipeline.intelligence.score,confidence:pipeline.intelligence.confidence,signal:pipeline.intelligence.signal,drivers:pipeline.intelligence.evidence,regime:pipeline.intelligence.regime,cycle:{phase:cycle.phase,priorTop:c.bullMarket?.priorTop,nextTop:c.bullMarket?.estimatedTop,bottomWindow:c.bearMarket?.bottomWindow,bottomProbability:cycle.bottomProbability,topProbability:cycle.topProbability},market:{rsi,trend:analysis.indicators?.trend,macd:analysis.indicators?.macd,support:analysis.technicalIndicators?.support,resistance:analysis.technicalIndicators?.resistance,bullTopRisk:c.bullMarket?.topRiskScore,breadthScore:breadth,derivativesRisk:derivatives.leverageRisk,crowding:derivatives.crowding,crossAssetRegime:cross.regime},dataQuality:pipeline.intelligence.dataQuality,engine:{score:pipeline.intelligence.score,confidence:pipeline.intelligence.confidence,scenario:pipeline.forecast.scenario},source:analysis.source||"a3-engine",generatedAt:new Date().toISOString()})}catch(e){console.error("Intelligence API error",e);return NextResponse.json({error:"Unable to generate intelligence"},{status:500})}}