import { type NextRequest, NextResponse } from "next/server"

interface CachedData { data: any; timestamp: number }
interface APIStatus { disabled: boolean; disabledUntil: number; reason?: string }

const dataCache = new Map<string, CachedData>()
const CACHE_DURATION = 600000
const apiStatus = new Map<string, APIStatus>()
const apiUsage = new Map<string, { count: number; resetTime: number }>()
const FALLBACK_DATA: Record<string, any> = { BTC:{symbol:"BTC",price:87500,change24h:1.2,volume24h:25000000000,source:"Cached"},ETH:{symbol:"ETH",price:3200,change24h:.8,volume24h:12000000000,source:"Cached"},SOL:{symbol:"SOL",price:195,change24h:2.1,volume24h:3500000000,source:"Cached"},AAPL:{symbol:"AAPL",price:185,change24h:.3,volume24h:45000000,source:"Cached"},TSLA:{symbol:"TSLA",price:245,change24h:-.5,volume24h:85000000,source:"Cached"},"EUR/USD":{symbol:"EUR/USD",price:1.08,change24h:.1,volume24h:0,source:"Cached"}}

function isAPIDisabled(name:string){const status=apiStatus.get(name);if(!status||!status.disabled)return false;if(Date.now()>status.disabledUntil){apiStatus.delete(name);return false}return true}
function disableAPI(name:string,durationMs:number,reason:string){console.log(`[market-data] disabling ${name}: ${reason}`);apiStatus.set(name,{disabled:true,disabledUntil:Date.now()+durationMs,reason})}
function canUseAPI(name:string,limit:number){if(isAPIDisabled(name))return false;const now=Date.now(),usage=apiUsage.get(name);if(!usage||now>usage.resetTime){apiUsage.set(name,{count:1,resetTime:now+60000});return true}if(usage.count<limit){usage.count++;return true}return false}
function getCachedData(symbol:string){const cached=dataCache.get(symbol.toUpperCase());return cached&&Date.now()-cached.timestamp<CACHE_DURATION?cached.data:null}
function setCachedData(symbol:string,data:any){dataCache.set(symbol.toUpperCase(),{data,timestamp:Date.now()})}
function getStaleCachedData(symbol:string){const cached=dataCache.get(symbol.toUpperCase());return cached?{...cached.data,stale:true}:null}

async function fetchFromTwelveData(symbol:string){const apiKey=process.env.TWELVE_DATA_API_KEY;if(!apiKey)throw new Error("provider unavailable");let formatted=symbol.toUpperCase();const commodityMap:Record<string,string>={GOLD:"XAU/USD",SILVER:"XAG/USD",OIL:"USOIL",CRUDE:"USOIL"};if(commodityMap[formatted])formatted=commodityMap[formatted];else if(["BTC","ETH","SOL","USDT","BNB","XRP","ADA","DOGE","MATIC","DOT"].includes(formatted))formatted=`${formatted}/USD`;const response=await fetch(`https://api.twelvedata.com/quote?symbol=${formatted}&apikey=${apiKey}`,{cache:"no-store"});if(!response.ok)throw new Error("provider request failed");const data=await response.json();if(data.status==="error"){if(String(data.message||"").includes("API credits"))disableAPI("TwelveData",60000,"rate limit");throw new Error("provider request failed")}return{source:"TwelveData",symbol:symbol.toUpperCase(),price:Number.parseFloat(data.close),change24h:Number.parseFloat(data.percent_change)||0,volume24h:Number.parseFloat(data.volume)||0,timestamp:Date.now()}}
async function fetchFromCoinGecko(symbol:string){const map:Record<string,string>={BTC:"bitcoin",ETH:"ethereum",SOL:"solana",USDT:"tether",BNB:"binancecoin",XRP:"ripple",ADA:"cardano",DOGE:"dogecoin"};const coinId=map[symbol.toUpperCase()];if(!coinId)throw new Error("provider unavailable");const response=await fetch(`https://api.coingecko.com/api/v3/simple/price?ids=${coinId}&vs_currencies=usd&include_24hr_change=true&include_24hr_vol=true`,{cache:"no-store"});if(response.status===429){disableAPI("CoinGecko",3600000,"rate limit");throw new Error("provider request failed")}if(!response.ok)throw new Error("provider request failed");const data=await response.json(),coin=data[coinId];if(!coin)throw new Error("provider request failed");return{source:"CoinGecko",symbol:symbol.toUpperCase(),price:coin.usd,change24h:coin.usd_24h_change||0,volume24h:coin.usd_24h_vol||0,timestamp:Date.now()}}

export async function GET(req:NextRequest){try{const symbol=new URL(req.url).searchParams.get("symbol");if(!symbol)return NextResponse.json({error:"Symbol parameter is required"},{status:400});const cached=getCachedData(symbol);if(cached)return NextResponse.json(cached);const sources=[{name:"TwelveData",fetchData:fetchFromTwelveData,rateLimit:6},{name:"CoinGecko",fetchData:fetchFromCoinGecko,rateLimit:25}];for(const source of sources){if(isAPIDisabled(source.name)||!canUseAPI(source.name,source.rateLimit))continue;try{const data=await source.fetchData(symbol);setCachedData(symbol,data);return NextResponse.json(data)}catch{continue}}const stale=getStaleCachedData(symbol);if(stale)return NextResponse.json(stale);const fallback=FALLBACK_DATA[symbol.toUpperCase()];if(fallback)return NextResponse.json({...fallback,timestamp:Date.now(),source:"Fallback"});return NextResponse.json({error:"Unable to fetch market data"},{status:503})}catch(error){console.error("[market-data] request failed",error);return NextResponse.json({error:"Failed to fetch market data"},{status:500})}}
